// KaTeX stretchy-SVG path geometry: wide accents, arrows, and braces.
//
// Ported from RaTeX `katex_svg.rs`. Raw path data lives in
// `KaTeXSvgData.swift` (generated by `scripts/gen_katex_svg_data.py`).


/// Returns (commands, width, height, fill) for a KaTeX SVG accent, or `nil` if unhandled.
///
/// `groupLen` is KaTeX’s `groupLength(base)` (`ordgroup.body.length`) for `\widehat` /
/// `\widecheck` / `\widetilde` / `\utilde` — variant choice uses this, not base width.
func katexAccentPath(
    _ label: String, baseWidthEm: Double, groupLen: Int
) -> (commands: [PathCommand], width: Double, height: Double, fill: Bool)? {
    switch label {
    case "\\vec":
        // KaTeX `svgGeometry.path.vec` (glyph U+20D7) + `svgData.vec` fixed size — not stretched to base width.
        let wEm = 0.471
        let hEm = 0.714
        let raw = parseSvgPath(KaTeXSvgData.katexVecPath)
        let cmds = raw.scaled(by: 0.001)
        return (cmds, wEm, hEm, true)
    case "\\widehat", "\\widecheck":
        let isHat = label == "\\widehat"
        let (path, vbW, vbH, hEm) = selectHatCheck(isHat: isHat, groupLen: groupLen)
        let cmds = parseAndFitNonuniform(
            path, vbWidth: vbW, vbHeight: vbH,
            targetWidthEm: baseWidthEm, targetHeightEm: hEm)
        return (cmds, baseWidthEm, hEm, true)
    case "\\widetilde", "\\utilde":
        let (path, vbW, vbH, hEm) = selectTilde(groupLen: groupLen)
        let cmds = parseAndFitNonuniform(
            path, vbWidth: vbW, vbHeight: vbH,
            targetWidthEm: baseWidthEm, targetHeightEm: hEm)
        return (cmds, baseWidthEm, hEm, true)
    case "\\overgroup":
        // KaTeX: viewBoxHeight=342, height=0.342
        let hEm = 0.342
        let cmds = buildOvergroup(widthEm: baseWidthEm, hEm: hEm, isOver: true)
        return (cmds, baseWidthEm, hEm, true)
    case "\\undergroup":
        let hEm = 0.342
        let cmds = buildOvergroup(widthEm: baseWidthEm, hEm: hEm, isOver: false)
        return (cmds, baseWidthEm, hEm, true)
    default:
        return nil
    }
}

/// Returns path commands for KaTeX stretchy arrows. Delegates to `katexStretchyPath`.
/// Kept for backward compatibility with existing callers.
func katexStretchyArrowPath(
    _ label: String, widthEm: Double, heightEm _: Double
) -> [PathCommand]? {
    katexStretchyPath(label, widthEm: widthEm).map { $0.commands }
}

func scaleCmdTwoheadUniform(
    _ cmd: PathCommand, s: Double, vbCy: Double, xShift: Double
) -> PathCommand {
    switch cmd {
    case .moveTo(let x, let y):
        .moveTo(x: x * s + xShift, y: (y - vbCy) * s)
    case .lineTo(let x, let y):
        .lineTo(x: x * s + xShift, y: (y - vbCy) * s)
    case .cubicTo(let x1, let y1, let x2, let y2, let x, let y):
        .cubicTo(
            x1: x1 * s + xShift, y1: (y1 - vbCy) * s,
            x2: x2 * s + xShift, y2: (y2 - vbCy) * s,
            x: x * s + xShift, y: (y - vbCy) * s)
    case .quadTo(let x1, let y1, let x, let y):
        .quadTo(
            x1: x1 * s + xShift, y1: (y1 - vbCy) * s,
            x: x * s + xShift, y: (y - vbCy) * s)
    case .close:
        .close
    }
}

/// Clip path to rectangle [xMin, xMax] x [yMin, yMax]. Curves are flattened then clipped.
/// For filled closed contours, the clip boundary edges are implicitly added by emitting
/// LineTo(a) whenever the start of a newly-visible segment doesn't match the current position.
func clipPathToRect(
    _ commands: [PathCommand],
    xMin: Double, xMax: Double, yMin: Double, yMax: Double
) -> [PathCommand] {
    let contours = flattenPathToContours(commands)
    var out: [PathCommand] = []
    for contour in contours {
        if contour.count < 2 {
            continue
        }
        var needMove = true
        var lastPt: (Double, Double) = (Double.nan, Double.nan)

        let n = contour.count
        // Process all n edges: 0→1, 1→2, …, (n-1)→0 (closing edge).
        for i in 0..<n {
            let p0 = contour[i]
            let p1 = contour[(i + 1) % n]
            let segments = clipSegmentToRect(p0, p1, xMin: xMin, xMax: xMax, yMin: yMin, yMax: yMax)
            for (a, b) in segments {
                if needMove {
                    out.append(.moveTo(x: a.0, y: a.1))
                    needMove = false
                } else if abs(a.0 - lastPt.0) > 1e-9 || abs(a.1 - lastPt.1) > 1e-9 {
                    // Gap due to clipped-away segments: emit the clip-boundary start point
                    // so the contour remains closed and the clip edge is explicitly drawn.
                    out.append(.lineTo(x: a.0, y: a.1))
                }
                out.append(.lineTo(x: b.0, y: b.1))
                lastPt = b
            }
        }
    }
    return out
}

func flattenPathToContours(_ commands: [PathCommand]) -> [[(Double, Double)]] {
    var contours: [[(Double, Double)]] = []
    var current: [(Double, Double)] = []
    var last: (Double, Double) = (0.0, 0.0)
    let n = 16  // steps per curve

    for cmd in commands {
        switch cmd {
        case .moveTo(let x, let y):
            if !current.isEmpty {
                contours.append(current)
                current = []
            }
            last = (x, y)
            current.append(last)
        case .lineTo(let x, let y):
            last = (x, y)
            current.append(last)
        case .cubicTo(let x1, let y1, let x2, let y2, let x, let y):
            let (x0, y0) = last
            for k in 1...n {
                let t = Double(k) / Double(n)
                let u = 1.0 - t
                let px =
                    u * u * u * x0
                    + 3.0 * u * u * t * x1
                    + 3.0 * u * t * t * x2
                    + t * t * t * x
                let py =
                    u * u * u * y0
                    + 3.0 * u * u * t * y1
                    + 3.0 * u * t * t * y2
                    + t * t * t * y
                last = (px, py)
                current.append(last)
            }
        case .quadTo(let x1, let y1, let x, let y):
            let (x0, y0) = last
            for k in 1...n {
                let t = Double(k) / Double(n)
                let u = 1.0 - t
                let px = u * u * x0 + 2.0 * u * t * x1 + t * t * x
                let py = u * u * y0 + 2.0 * u * t * y1 + t * t * y
                last = (px, py)
                current.append(last)
            }
        case .close:
            if !current.isEmpty {
                contours.append(current)
                current = []
            }
        }
    }
    if !current.isEmpty {
        contours.append(current)
    }
    return contours
}

/// Clip line segment (p0,p1) to rectangle. Returns 0 or 1 segment (as (start,end)) inside the rect.
/// Uses Liang-Barsky.
private func clipSegmentToRect(
    _ p0: (Double, Double), _ p1: (Double, Double),
    xMin: Double, xMax: Double, yMin: Double, yMax: Double
) -> [((Double, Double), (Double, Double))] {
    let (x0, y0) = p0
    let (x1, y1) = p1
    let dx = x1 - x0
    let dy = y1 - y0
    var t0 = 0.0
    var t1 = 1.0

    func clip(_ p: Double, _ q: Double) -> Bool {
        if abs(p) < 1e-12 {
            return q >= 0.0
        }
        let t = q / p
        if p < 0.0 {
            if t > t1 {
                return false
            }
            if t > t0 {
                t0 = t
            }
        } else {
            if t < t0 {
                return false
            }
            if t < t1 {
                t1 = t
            }
        }
        return true
    }

    if !clip(-dx, x0 - xMin) {
        return []
    }
    if !clip(dx, xMax - x0) {
        return []
    }
    if !clip(-dy, y0 - yMin) {
        return []
    }
    if !clip(dy, yMax - y0) {
        return []
    }

    if t0 >= t1 - 1e-9 {
        return []
    }
    let a = (x0 + t0 * dx, y0 + t0 * dy)
    let b = (x0 + t1 * dx, y0 + t1 * dy)
    return [(a, b)]
}

/// KaTeX `svgSpan` / `svgGeometry.js`: `imgIndex = [1,1,2,2,3,3][numChars]` for `numChars` ≤ 5;
/// `numChars > 5` uses the fourth (widest/tallest) asset.
private func wideAccentImgIndex(_ groupLen: Int) -> Int {
    if groupLen > 5 {
        4
    } else {
        [1, 1, 2, 2, 3, 3][groupLen]
    }
}

private func selectHatCheck(isHat: Bool, groupLen: Int) -> (String, Double, Double, Double) {
    let imgIndex = wideAccentImgIndex(groupLen)
    let prefix = isHat ? KaTeXSvgData.widehat : KaTeXSvgData.widecheck
    let vbW = [0.0, 1062.0, 2364.0, 2364.0, 2364.0][imgIndex]
    let vbH = [0.0, 239.0, 300.0, 360.0, 420.0][imgIndex]
    // KaTeX: `_height = [0, 0.24, 0.3, 0.3, 0.36, 0.42][imgIndex]`; `numChars > 5` forces 0.42.
    let hEm =
        if groupLen > 5 {
            0.42
        } else {
            [0.0, 0.24, 0.3, 0.3, 0.36, 0.42][imgIndex]
        }
    return (prefix[imgIndex - 1], vbW, vbH, hEm)
}

private func selectTilde(groupLen: Int) -> (String, Double, Double, Double) {
    let imgIndex = wideAccentImgIndex(groupLen)
    let vbW = [0.0, 600.0, 1033.0, 2339.0, 2340.0][imgIndex]
    let vbH = [0.0, 260.0, 286.0, 306.0, 312.0][imgIndex]
    let hEm =
        if groupLen > 5 {
            0.34
        } else {
            [0.0, 0.26, 0.286, 0.3, 0.306, 0.34][imgIndex]
        }
    return (KaTeXSvgData.tilde[imgIndex - 1], vbW, vbH, hEm)
}

/// Parse SVG path and scale with independent X/Y factors (preserveAspectRatio="none").
private func parseAndFitNonuniform(
    _ svgPath: String,
    vbWidth: Double, vbHeight: Double,
    targetWidthEm: Double, targetHeightEm: Double
) -> [PathCommand] {
    let raw = parseSvgPath(svgPath)
    let sx = targetWidthEm / vbWidth
    let sy = targetHeightEm / vbHeight
    return raw.map { scaleCmdXY($0, sx: sx, sy: sy) }
}

/// Build the overgroup/undergroup filled path from KaTeX leftgroup/rightgroup data.
private func buildOvergroup(widthEm: Double, hEm: Double, isOver: Bool) -> [PathCommand] {
    // KaTeX overgroup: left half = leftgroup, right half = rightgroup
    // viewBox: 400000 × 342, height = 0.342em
    // We combine both halves into a single filled path.
    //
    // leftgroup outer curve (in viewBox units):
    //   (435, 80) → C(64,80)(168.3,229.4)(21,260) → small curves → (0,257) → V(0,219)
    //   Inner: (0,219) → C(76,61)(257,0)(435,0) → H to right → close
    //
    // rightgroup: mirror at the right end.
    let vbH = 342.0
    let sy = hEm / vbH

    // KaTeX's curves span 0..435 viewBox units at each end.
    // At 1000:1 scale, 435 units = 0.435em. Keep this natural size.
    // If the target is too narrow, shrink corners proportionally.
    let naturalCorner = 0.435
    let cornerEm = min(naturalCorner, widthEm / 2.0)
    // cx converts curve x-coordinates (0..435) to em
    let cx = cornerEm / 435.0

    func ly(_ y: Double) -> Double { y * sy }

    if isOver {
        return [
            // Start at top-left, after corner
            .moveTo(x: cornerEm, y: ly(80.0)),
            // Left outer curve down
            .cubicTo(
                x1: 64.0 * cx, y1: ly(80.0),
                x2: 168.3 * cx, y2: ly(229.4),
                x: 21.0 * cx, y: ly(260.0)),
            .cubicTo(
                x1: 15.1 * cx, y1: ly(261.2),
                x2: 3.0 * cx, y2: ly(260.0),
                x: 3.0 * cx, y: ly(260.0)),
            .cubicTo(
                x1: 1.0 * cx, y1: ly(260.0),
                x2: 0.0, y2: ly(259.0),
                x: 0.0, y: ly(257.0)),
            .lineTo(x: 0.0, y: ly(219.0)),
            // Left inner curve up
            .cubicTo(
                x1: 76.0 * cx, y1: ly(61.0),
                x2: 257.0 * cx, y2: ly(0.0),
                x: cornerEm, y: ly(0.0)),
            // Bottom flat section
            .lineTo(x: widthEm - cornerEm, y: ly(0.0)),
            // Right inner curve down
            .cubicTo(
                x1: widthEm - 257.0 * cx, y1: ly(0.0),
                x2: widthEm - 76.0 * cx, y2: ly(61.0),
                x: widthEm, y: ly(219.0)),
            .lineTo(x: widthEm, y: ly(257.0)),
            // Right outer curves up
            .cubicTo(
                x1: widthEm, y1: ly(259.0),
                x2: widthEm - 1.0 * cx, y2: ly(260.0),
                x: widthEm - 3.0 * cx, y: ly(260.0)),
            .cubicTo(
                x1: widthEm - 3.0 * cx, y1: ly(260.0),
                x2: widthEm - 15.1 * cx, y2: ly(261.2),
                x: widthEm - 21.0 * cx, y: ly(260.0)),
            .cubicTo(
                x1: widthEm - 168.3 * cx, y1: ly(229.4),
                x2: widthEm - 64.0 * cx, y2: ly(80.0),
                x: widthEm - cornerEm, y: ly(80.0)),
            .close,
        ]
    } else {
        // undergroup: KaTeX leftgroupunder / rightgroupunder
        // leftgroupunder:
        //   (435, 262) → C(64,262)(168.3,112.6)(21,82) → curves → (0,85) → V(0,123)
        //   Inner: (0,123) → C(76,281)(257,342)(435,342) → H → close
        return [
            .moveTo(x: cornerEm, y: ly(262.0)),
            .cubicTo(
                x1: 64.0 * cx, y1: ly(262.0),
                x2: 168.3 * cx, y2: ly(112.6),
                x: 21.0 * cx, y: ly(82.0)),
            .cubicTo(
                x1: 15.1 * cx, y1: ly(80.8),
                x2: 3.0 * cx, y2: ly(82.0),
                x: 3.0 * cx, y: ly(82.0)),
            .cubicTo(
                x1: 1.0 * cx, y1: ly(82.0),
                x2: 0.0, y2: ly(83.0),
                x: 0.0, y: ly(85.0)),
            .lineTo(x: 0.0, y: ly(123.0)),
            .cubicTo(
                x1: 76.0 * cx, y1: ly(281.0),
                x2: 257.0 * cx, y2: ly(342.0),
                x: cornerEm, y: ly(342.0)),
            .lineTo(x: widthEm - cornerEm, y: ly(342.0)),
            .cubicTo(
                x1: widthEm - 257.0 * cx, y1: ly(342.0),
                x2: widthEm - 76.0 * cx, y2: ly(281.0),
                x: widthEm, y: ly(123.0)),
            .lineTo(x: widthEm, y: ly(85.0)),
            .cubicTo(
                x1: widthEm, y1: ly(83.0),
                x2: widthEm - 1.0 * cx, y2: ly(82.0),
                x: widthEm - 3.0 * cx, y: ly(82.0)),
            .cubicTo(
                x1: widthEm - 3.0 * cx, y1: ly(82.0),
                x2: widthEm - 15.1 * cx, y2: ly(80.8),
                x: widthEm - 21.0 * cx, y: ly(82.0)),
            .cubicTo(
                x1: widthEm - 168.3 * cx, y1: ly(112.6),
                x2: widthEm - 64.0 * cx, y2: ly(262.0),
                x: widthEm - cornerEm, y: ly(262.0)),
            .close,
        ]
    }
}

func scaleCmdXY(_ cmd: PathCommand, sx: Double, sy: Double) -> PathCommand {
    switch cmd {
    case .moveTo(let x, let y):
        .moveTo(x: x * sx, y: y * sy)
    case .lineTo(let x, let y):
        .lineTo(x: x * sx, y: y * sy)
    case .cubicTo(let x1, let y1, let x2, let y2, let x, let y):
        .cubicTo(x1: x1 * sx, y1: y1 * sy, x2: x2 * sx, y2: y2 * sy, x: x * sx, y: y * sy)
    case .quadTo(let x1, let y1, let x, let y):
        .quadTo(x1: x1 * sx, y1: y1 * sy, x: x * sx, y: y * sy)
    case .close:
        .close
    }
}

// ---------------------------------------------------------------------------
// Minimal SVG path data parser
// ---------------------------------------------------------------------------

/// Parse a KaTeX-style SVG path `d` string into ``PathCommand``s (for delimiters, accents).
func parseSvgPathData(_ d: String) -> [PathCommand] {
    parseSvgPath(d)
}

/// Memoized front-end for `parseSvgPathUncached` (P-020). Every `d` string
/// reaching layout is either a static KaTeX table entry or generated from a
/// template with an integer mid-section parameter, so identical strings
/// recur constantly (across formulas sharing delimiter heights, and within
/// multi-piece images). Tokenize+parse showed up at ~5 % of engine profiles;
/// a string-keyed memo turns repeats into one hash of the `d` string.
/// Returned arrays are value types — callers may mutate their copies freely.
private let svgPathMemo = Mutex<[String: [PathCommand]]>([:])

func parseSvgPath(_ d: String) -> [PathCommand] {
    svgPathMemo.withLock { cache in
        if let hit = cache[d] {
            return hit
        }
        let parsed = parseSvgPathUncached(d)
        if cache.count >= 512 {
            cache.removeAll(keepingCapacity: true)
        }
        cache[d] = parsed
        return parsed
    }
}

private func parseSvgPathUncached(_ d: String) -> [PathCommand] {
    let tokens = tokenizeSvg(d)
    var cmds: [PathCommand] = []
    var i = 0
    var cx = 0.0
    var cy = 0.0
    var subpathStart: (Double, Double) = (0.0, 0.0)
    var lastCmd = UInt8(ascii: "M")

    while i < tokens.count {
        let cmdByte: UInt8
        switch tokens[i] {
        case .cmd(let c):
            i += 1
            cmdByte = c
        case .num:
            cmdByte = lastCmd
        }

        switch cmdByte {
        case UInt8(ascii: "M"):
            let (x, y) = read2(tokens, &i)
            cx = x
            cy = y
            subpathStart = (cx, cy)
            cmds.append(.moveTo(x: x, y: y))
            lastCmd = UInt8(ascii: "L")
        case UInt8(ascii: "m"):
            let (dx, dy) = read2(tokens, &i)
            cx += dx
            cy += dy
            subpathStart = (cx, cy)
            cmds.append(.moveTo(x: cx, y: cy))
            lastCmd = UInt8(ascii: "l")
        case UInt8(ascii: "L"):
            let (x, y) = read2(tokens, &i)
            cx = x
            cy = y
            cmds.append(.lineTo(x: x, y: y))
            lastCmd = UInt8(ascii: "L")
        case UInt8(ascii: "l"):
            let (dx, dy) = read2(tokens, &i)
            cx += dx
            cy += dy
            cmds.append(.lineTo(x: cx, y: cy))
            lastCmd = UInt8(ascii: "l")
        case UInt8(ascii: "H"):
            let x = read1(tokens, &i)
            cx = x
            cmds.append(.lineTo(x: cx, y: cy))
            lastCmd = UInt8(ascii: "H")
        case UInt8(ascii: "h"):
            let dx = read1(tokens, &i)
            cx += dx
            cmds.append(.lineTo(x: cx, y: cy))
            lastCmd = UInt8(ascii: "h")
        case UInt8(ascii: "V"):
            let y = read1(tokens, &i)
            cy = y
            cmds.append(.lineTo(x: cx, y: cy))
            lastCmd = UInt8(ascii: "V")
        case UInt8(ascii: "v"):
            let dy = read1(tokens, &i)
            cy += dy
            cmds.append(.lineTo(x: cx, y: cy))
            lastCmd = UInt8(ascii: "v")
        case UInt8(ascii: "C"):
            let (x1, y1) = read2(tokens, &i)
            let (x2, y2) = read2(tokens, &i)
            let (x, y) = read2(tokens, &i)
            cx = x
            cy = y
            cmds.append(.cubicTo(x1: x1, y1: y1, x2: x2, y2: y2, x: x, y: y))
            lastCmd = UInt8(ascii: "C")
        case UInt8(ascii: "c"):
            let (dx1, dy1) = read2(tokens, &i)
            let (dx2, dy2) = read2(tokens, &i)
            let (dx, dy) = read2(tokens, &i)
            let x1 = cx + dx1
            let y1 = cy + dy1
            let x2 = cx + dx2
            let y2 = cy + dy2
            cx += dx
            cy += dy
            cmds.append(.cubicTo(x1: x1, y1: y1, x2: x2, y2: y2, x: cx, y: cy))
            lastCmd = UInt8(ascii: "c")
        case UInt8(ascii: "S"):
            let (x2, y2) = read2(tokens, &i)
            let (x, y) = read2(tokens, &i)
            let x1 = cx
            let y1 = cy
            cx = x
            cy = y
            cmds.append(.cubicTo(x1: x1, y1: y1, x2: x2, y2: y2, x: x, y: y))
            lastCmd = UInt8(ascii: "S")
        case UInt8(ascii: "s"):
            let (dx2, dy2) = read2(tokens, &i)
            let (dx, dy) = read2(tokens, &i)
            let x1 = cx
            let y1 = cy
            let x2 = cx + dx2
            let y2 = cy + dy2
            cx += dx
            cy += dy
            cmds.append(.cubicTo(x1: x1, y1: y1, x2: x2, y2: y2, x: cx, y: cy))
            lastCmd = UInt8(ascii: "s")
        case UInt8(ascii: "Q"):
            let (x1, y1) = read2(tokens, &i)
            let (x, y) = read2(tokens, &i)
            cx = x
            cy = y
            cmds.append(.quadTo(x1: x1, y1: y1, x: x, y: y))
            lastCmd = UInt8(ascii: "Q")
        case UInt8(ascii: "q"):
            let (dx1, dy1) = read2(tokens, &i)
            let (dx, dy) = read2(tokens, &i)
            let x1 = cx + dx1
            let y1 = cy + dy1
            cx += dx
            cy += dy
            cmds.append(.quadTo(x1: x1, y1: y1, x: cx, y: cy))
            lastCmd = UInt8(ascii: "q")
        case UInt8(ascii: "Z"), UInt8(ascii: "z"):
            cmds.append(.close)
            // Per SVG spec: after closepath, current point returns to subpath start.
            cx = subpathStart.0
            cy = subpathStart.1
            lastCmd = UInt8(ascii: "M")
        default:
            i += 1
        }
    }
    return cmds
}

private enum SvgToken {
    case cmd(UInt8)
    case num(Double)
}

private func tokenizeSvg(_ d: String) -> [SvgToken] {
    var tokens: [SvgToken] = []
    let bytes = Array(d.utf8)
    var i = 0
    while i < bytes.count {
        let b = bytes[i]
        if isAsciiAlphabetic(b) {
            tokens.append(.cmd(b))
            i += 1
        } else if b == UInt8(ascii: "-") || b == UInt8(ascii: ".") || isAsciiDigit(b) {
            let start = i
            if b == UInt8(ascii: "-") {
                i += 1
            }
            var hasDot = false
            while i < bytes.count,
                isAsciiDigit(bytes[i]) || (bytes[i] == UInt8(ascii: ".") && !hasDot)
            {
                if bytes[i] == UInt8(ascii: ".") {
                    hasDot = true
                }
                i += 1
            }
            if let n = Double(String(decoding: bytes[start..<i], as: UTF8.self)) {
                tokens.append(.num(n))
            }
        } else {
            i += 1
        }
    }
    return tokens
}

private func isAsciiAlphabetic(_ b: UInt8) -> Bool {
    (UInt8(ascii: "A")...UInt8(ascii: "Z")).contains(b)
        || (UInt8(ascii: "a")...UInt8(ascii: "z")).contains(b)
}

private func isAsciiDigit(_ b: UInt8) -> Bool {
    (UInt8(ascii: "0")...UInt8(ascii: "9")).contains(b)
}

private func read1(_ tokens: [SvgToken], _ i: inout Int) -> Double {
    if i < tokens.count, case .num(let n) = tokens[i] {
        i += 1
        return n
    }
    return 0.0
}

private func read2(_ tokens: [SvgToken], _ i: inout Int) -> (Double, Double) {
    let a = read1(tokens, &i)
    let b = read1(tokens, &i)
    return (a, b)
}

// ---------------------------------------------------------------------------
// KaTeX images data lookup table (from katexImagesData in katex.js)
// ---------------------------------------------------------------------------

private struct KatexImageData {
    var paths: [String]
    /// KaTeX `katexImagesData` minimum arrow shaft width (em).
    var minWidth: Double
    var vbHeight: Double
    var align: String?
}

private func katexImageData(_ label: String) -> KatexImageData? {
    let key = label.hasPrefix("\\") ? String(label.drop(while: { $0 == "\\" })) : label
    switch key {
    case "overrightarrow":
        return KatexImageData(
            paths: ["rightarrow"], minWidth: 0.888, vbHeight: 522.0, align: "xMaxYMin")
    case "overleftarrow":
        return KatexImageData(
            paths: ["leftarrow"], minWidth: 0.888, vbHeight: 522.0, align: "xMinYMin")
    case "underrightarrow":
        return KatexImageData(
            paths: ["rightarrow"], minWidth: 0.888, vbHeight: 522.0, align: "xMaxYMin")
    case "underleftarrow":
        return KatexImageData(
            paths: ["leftarrow"], minWidth: 0.888, vbHeight: 522.0, align: "xMinYMin")
    case "xrightarrow":
        return KatexImageData(
            paths: ["rightarrow"], minWidth: 1.469, vbHeight: 522.0, align: "xMaxYMin")
    // KaTeX `stretchy.js` `katexImagesData`: `\cdrightarrow` / `\cdlongequal` use minWidth 3.0em
    // (comment “CD minwwidth2.5pc” — amscd `\minCDarrowwidth`, ~2.5pc ≈ 3em at 10pt).
    case "cdrightarrow":
        return KatexImageData(
            paths: ["rightarrow"], minWidth: 3.0, vbHeight: 522.0, align: "xMaxYMin")
    case "cdleftarrow":
        return KatexImageData(
            paths: ["leftarrow"], minWidth: 3.0, vbHeight: 522.0, align: "xMinYMin")
    case "xleftarrow":
        return KatexImageData(
            paths: ["leftarrow"], minWidth: 1.469, vbHeight: 522.0, align: "xMinYMin")
    case "Overrightarrow":
        return KatexImageData(
            paths: ["doublerightarrow"], minWidth: 0.888, vbHeight: 560.0, align: "xMaxYMin")
    case "xRightarrow":
        return KatexImageData(
            paths: ["doublerightarrow"], minWidth: 1.526, vbHeight: 560.0, align: "xMaxYMin")
    case "xLeftarrow":
        return KatexImageData(
            paths: ["doubleleftarrow"], minWidth: 1.526, vbHeight: 560.0, align: "xMinYMin")
    case "overleftharpoon", "xleftharpoonup":
        return KatexImageData(
            paths: ["leftharpoon"], minWidth: 0.888, vbHeight: 522.0, align: "xMinYMin")
    case "xleftharpoondown":
        return KatexImageData(
            paths: ["leftharpoondown"], minWidth: 0.888, vbHeight: 522.0, align: "xMinYMin")
    case "overrightharpoon", "xrightharpoonup":
        return KatexImageData(
            paths: ["rightharpoon"], minWidth: 0.888, vbHeight: 522.0, align: "xMaxYMin")
    case "xrightharpoondown":
        return KatexImageData(
            paths: ["rightharpoondown"], minWidth: 0.888, vbHeight: 522.0, align: "xMaxYMin")
    case "xlongequal":
        return KatexImageData(
            paths: ["longequal"], minWidth: 0.888, vbHeight: 334.0, align: "xMinYMin")
    case "cdlongequal":
        return KatexImageData(
            paths: ["longequal"], minWidth: 3.0, vbHeight: 334.0, align: "xMinYMin")
    case "xtwoheadleftarrow":
        return KatexImageData(
            paths: ["twoheadleftarrow"], minWidth: 0.888, vbHeight: 334.0, align: "xMinYMin")
    case "xtwoheadrightarrow":
        return KatexImageData(
            paths: ["twoheadrightarrow"], minWidth: 0.888, vbHeight: 334.0, align: "xMaxYMin")
    case "overleftrightarrow":
        return KatexImageData(
            paths: ["leftarrow", "rightarrow"], minWidth: 0.888, vbHeight: 522.0, align: nil)
    case "underleftrightarrow":
        return KatexImageData(
            paths: ["leftarrow", "rightarrow"], minWidth: 0.888, vbHeight: 522.0, align: nil)
    case "xleftrightarrow":
        return KatexImageData(
            paths: ["leftarrow", "rightarrow"], minWidth: 1.75, vbHeight: 522.0, align: nil)
    case "xLeftrightarrow":
        return KatexImageData(
            paths: ["doubleleftarrow", "doublerightarrow"], minWidth: 1.75, vbHeight: 560.0,
            align: nil)
    case "xrightleftharpoons":
        return KatexImageData(
            paths: ["leftharpoondownplus", "rightharpoonplus"], minWidth: 1.75, vbHeight: 716.0,
            align: nil)
    case "xleftrightharpoons":
        return KatexImageData(
            paths: ["leftharpoonplus", "rightharpoondownplus"], minWidth: 1.75, vbHeight: 716.0,
            align: nil)
    case "xrightequilibrium":
        return KatexImageData(
            paths: ["baraboveshortleftharpoon", "rightharpoonaboveshortbar"], minWidth: 1.75,
            vbHeight: 716.0, align: nil)
    case "xleftequilibrium":
        return KatexImageData(
            paths: ["shortbaraboveleftharpoon", "shortrightharpoonabovebar"], minWidth: 1.75,
            vbHeight: 716.0, align: nil)
    case "xhookleftarrow":
        return KatexImageData(
            paths: ["leftarrow", "righthook"], minWidth: 1.08, vbHeight: 522.0, align: nil)
    case "xhookrightarrow":
        return KatexImageData(
            paths: ["lefthook", "rightarrow"], minWidth: 1.08, vbHeight: 522.0, align: nil)
    case "overlinesegment":
        return KatexImageData(
            paths: ["leftlinesegment", "rightlinesegment"], minWidth: 0.888, vbHeight: 522.0,
            align: nil)
    case "underlinesegment":
        return KatexImageData(
            paths: ["leftlinesegment", "rightlinesegment"], minWidth: 0.888, vbHeight: 522.0,
            align: nil)
    case "overgroup":
        return KatexImageData(
            paths: ["leftgroup", "rightgroup"], minWidth: 0.888, vbHeight: 342.0, align: nil)
    case "undergroup":
        return KatexImageData(
            paths: ["leftgroupunder", "rightgroupunder"], minWidth: 0.888, vbHeight: 342.0,
            align: nil)
    case "xmapsto":
        return KatexImageData(
            paths: ["leftmapsto", "rightarrow"], minWidth: 1.5, vbHeight: 522.0, align: nil)
    case "xtofrom":
        return KatexImageData(
            paths: ["leftToFrom", "rightToFrom"], minWidth: 1.75, vbHeight: 528.0, align: nil)
    case "xrightleftarrows":
        return KatexImageData(
            paths: ["baraboveleftarrow", "rightarrowabovebar"], minWidth: 1.75, vbHeight: 901.0,
            align: nil)
    // Overbrace/underbrace: KaTeX Size4 glyphs (viewBox 400000×548), same 3-piece horizontal joining as stretchy arrows.
    case "overbrace":
        return KatexImageData(
            paths: ["leftbrace", "midbrace", "rightbrace"], minWidth: 0.888, vbHeight: 548.0,
            align: nil)
    case "underbrace":
        return KatexImageData(
            paths: ["leftbraceunder", "midbraceunder", "rightbraceunder"], minWidth: 0.888,
            vbHeight: 548.0, align: nil)
    // mathtools `\overbracket` / `\underbracket`: 2-piece KaTeX SVG (same minWidth/height as KaTeX `stretchy.ts`).
    case "overbracket":
        return KatexImageData(
            paths: ["leftbracketover", "rightbracketover"], minWidth: 1.6, vbHeight: 440.0,
            align: nil)
    case "underbracket":
        return KatexImageData(
            paths: ["leftbracketunder", "rightbracketunder"], minWidth: 1.6, vbHeight: 410.0,
            align: nil)
    default:
        return nil
    }
}

/// KaTeX [`katexImagesData`](https://github.com/KaTeX/KaTeX/blob/main/src/katexImagesData.js) `minWidth`
/// for `\xrightarrow`, `\xleftrightarrow`, mhchem `\xrightequilibrium`, etc.
func katexStretchyMinWidthEm(_ label: String) -> Double? {
    katexImageData(label).map { $0.minWidth }
}

/// Look up the SVG path data for a named path key.
private func pathForName(_ name: String) -> String? {
    switch name {
    case "rightarrow": KaTeXSvgData.rightarrow
    case "leftarrow": KaTeXSvgData.leftarrow
    case "doubleleftarrow": KaTeXSvgData.doubleleftarrow
    case "doublerightarrow": KaTeXSvgData.doublerightarrow
    case "leftharpoon": KaTeXSvgData.leftharpoon
    case "leftharpoonplus": KaTeXSvgData.leftharpoonplus
    case "leftharpoondown": KaTeXSvgData.leftharpoondown
    case "leftharpoondownplus": KaTeXSvgData.leftharpoondownplus
    case "rightharpoon": KaTeXSvgData.rightharpoon
    case "rightharpoonplus": KaTeXSvgData.rightharpoonplus
    case "rightharpoondown": KaTeXSvgData.rightharpoondown
    case "rightharpoondownplus": KaTeXSvgData.rightharpoondownplus
    case "baraboveshortleftharpoon": KaTeXSvgData.baraboveshortleftharpoon
    case "rightharpoonaboveshortbar": KaTeXSvgData.rightharpoonaboveshortbar
    case "shortbaraboveleftharpoon": KaTeXSvgData.shortbaraboveleftharpoon
    case "shortrightharpoonabovebar": KaTeXSvgData.shortrightharpoonabovebar
    case "lefthook": KaTeXSvgData.lefthook
    case "righthook": KaTeXSvgData.righthook
    case "leftbrace": KaTeXSvgData.leftbrace
    case "midbrace": KaTeXSvgData.midbrace
    case "rightbrace": KaTeXSvgData.rightbrace
    case "leftbraceunder": KaTeXSvgData.leftbraceunder
    case "midbraceunder": KaTeXSvgData.midbraceunder
    case "rightbraceunder": KaTeXSvgData.rightbraceunder
    case "leftToFrom": KaTeXSvgData.lefttofrom
    case "rightToFrom": KaTeXSvgData.righttofrom
    case "baraboveleftarrow": KaTeXSvgData.baraboveleftarrow
    case "rightarrowabovebar": KaTeXSvgData.rightarrowabovebar
    case "longequal": KaTeXSvgData.longequal
    case "leftlinesegment": KaTeXSvgData.leftlinesegment
    case "rightlinesegment": KaTeXSvgData.rightlinesegment
    case "leftmapsto": KaTeXSvgData.leftmapsto
    case "twoheadleftarrow": KaTeXSvgData.twoheadleftarrow
    case "twoheadrightarrow": KaTeXSvgData.twoheadrightarrow
    case "leftgroup": KaTeXSvgData.leftgroup
    case "leftgroupunder": KaTeXSvgData.leftgroupunder
    case "rightgroup": KaTeXSvgData.rightgroup
    case "rightgroupunder": KaTeXSvgData.rightgroupunder
    case "leftbracketover": KaTeXSvgData.leftbracketover
    case "rightbracketover": KaTeXSvgData.rightbracketover
    case "leftbracketunder": KaTeXSvgData.leftbracketunder
    case "rightbracketunder": KaTeXSvgData.rightbracketunder
    default: nil
    }
}

/// Memo key for `katexStretchyPath`. `widthEm` is keyed by bit pattern:
/// recurrences come from identical layout inputs, so they are bit-exact,
/// and bit-pattern equality sidesteps `Double`'s `-0.0 == 0.0` / NaN
/// hashing semantics (distinct keys at worst — the bound absorbs it).
private struct StretchyPathKey: Hashable {
    let label: String
    let widthBits: UInt64
}

/// Memoized front-end for `katexStretchyPathUncached` (P-028). The uncached
/// path re-runs parse → scale → flatten (16 steps/curve) → Liang–Barsky
/// clipping on every call — ~17 % of engine samples on the golden corpus —
/// while stretchy elements recur constantly at identical widths (repeated
/// notation, alignment rows, mhchem arrows). Same clear-on-overflow design
/// as the P-020 path memo, but bounded at 128: entries are 13–38 KB command
/// arrays (measured), so 128 caps worst-case residency at ~5 MB while real
/// documents use a few dozen distinct keys (the full golden corpus shows no
/// hit-rate loss vs 512). `nil` results are not cached (the miss path is a
/// single table probe). Returned arrays are value types — callers may
/// mutate their copies freely.
private let stretchyPathMemo = Mutex<
    [StretchyPathKey: (commands: [PathCommand], heightEm: Double)]
>([:])

/// Generalized KaTeX stretchy element renderer.
///
/// Returns `(commands, heightEm)` where commands are centered at y=0
/// (shaft/midline at y≈0, extending ±heightEm/2 above/below), or `nil` if
/// the label is not in the lookup table.
func katexStretchyPath(
    _ label: String, widthEm: Double
) -> (commands: [PathCommand], heightEm: Double)? {
    let key = StretchyPathKey(label: label, widthBits: widthEm.bitPattern)
    return stretchyPathMemo.withLock { cache in
        if let hit = cache[key] {
            return hit
        }
        guard let computed = katexStretchyPathUncached(label, widthEm: widthEm) else {
            return nil
        }
        if cache.count >= 128 {
            cache.removeAll(keepingCapacity: true)
        }
        cache[key] = computed
        return computed
    }
}

private func katexStretchyPathUncached(
    _ label: String, widthEm: Double
) -> (commands: [PathCommand], heightEm: Double)? {
    guard let data = katexImageData(label) else {
        return nil
    }
    let s = 1.0 / 1000.0
    let heightEm = data.vbHeight * s
    let vbCy = data.vbHeight / 2.0
    let yMin = -heightEm / 2.0
    let yMax = heightEm / 2.0

    func makeCmds(_ pathName: String, xShift: Double) -> [PathCommand]? {
        // INTENTIONALLY UNCOVERED (defensive-fallback KEEP, this guard and
        // the three `guard … makeCmds` else-branches below): every path
        // name referenced by a `katexImageData` entry resolves in
        // `pathForName` (both are static generated tables), so `makeCmds`
        // never returns nil. Kept so a future table edit fails soft (nil →
        // caller's hand-drawn fallback) instead of crashing.
        guard let svgStr = pathForName(pathName) else {
            return nil
        }
        let raw = parseSvgPath(svgStr)
        return raw.map { scaleCmdTwoheadUniform($0, s: s, vbCy: vbCy, xShift: xShift) }
    }

    switch data.paths.count {
    case 1:
        let xShift = data.align == "xMaxYMin" ? widthEm - 400_000.0 * s : 0.0
        guard let cmds = makeCmds(data.paths[0], xShift: xShift) else {
            // INTENTIONALLY UNCOVERED (defensive guard KEEP — see makeCmds).
            return nil
        }
        return (
            clipPathToRect(cmds, xMin: 0.0, xMax: widthEm, yMin: yMin, yMax: yMax),
            heightEm
        )
    case 2:
        let xR = widthEm - 400_000.0 * s
        guard let lc = makeCmds(data.paths[0], xShift: 0.0),
            let rc = makeCmds(data.paths[1], xShift: xR)
        else {
            // INTENTIONALLY UNCOVERED (defensive guard KEEP — see makeCmds).
            return nil
        }
        let isXmapsto = data.paths[0] == "leftmapsto" && data.paths[1] == "rightarrow"
        let out: [PathCommand]
        if isXmapsto {
            // xmapsto: draw as one path so the horizontal shaft is guaranteed. KaTeX LEFTMAPSTO
            // has vertical bar at x=0..40 and shaft 40..400000; we draw left bar only, then
            // explicit shaft rect (from KaTeX viewBox 400000×522: y 241–281), then right arrow.
            // Shaft must not extend left of the vertical bar: use shaft_x_end >= left_bar_x_max.
            // Start the shaft slightly left of left_bar_x_max (~1px) so the intersection pixel
            // with the vertical bar is not clipped away by the boundary.
            let leftBarXMax = 40.0 * s  // 0.04 em, right edge of left vertical bar
            let shaftOverlap = 0.1  // ~1px in em to keep the corner pixel
            let shaftXStart = max(leftBarXMax - shaftOverlap, 0.0)
            let shaftYTop = (241.0 - vbCy) * s
            let shaftYBot = (281.0 - vbCy) * s
            let shaftXEnd = max(xR, leftBarXMax)
            var cmds = clipPathToRect(lc, xMin: 0.0, xMax: leftBarXMax, yMin: yMin, yMax: yMax)
            if shaftXEnd > shaftXStart {
                cmds.append(.moveTo(x: shaftXStart, y: shaftYTop))
                cmds.append(.lineTo(x: shaftXEnd, y: shaftYTop))
                cmds.append(.lineTo(x: shaftXEnd, y: shaftYBot))
                cmds.append(.lineTo(x: shaftXStart, y: shaftYBot))
                cmds.append(.close)
            }
            cmds.append(
                contentsOf: clipPathToRect(rc, xMin: 0.0, xMax: widthEm, yMin: yMin, yMax: yMax))
            out = cmds
        } else {
            // Split at the midpoint so each half-arrow's shaft bars don't extend
            // into the opposite arrowhead region.  The left path owns [0, mid]
            // and the right path owns [mid, width_em].  This prevents shaft bar
            // rectangles from covering the opposite arrowhead (e.g. doubleleftarrow
            // shaft bars covering the doublerightarrow arrowhead area).
            let mid = widthEm / 2.0
            var cmds = clipPathToRect(lc, xMin: 0.0, xMax: mid, yMin: yMin, yMax: yMax)
            cmds.append(
                contentsOf: clipPathToRect(rc, xMin: mid, xMax: widthEm, yMin: yMin, yMax: yMax))
            out = cmds
        }
        return (out, heightEm)
    case 3:
        let xM = widthEm / 2.0 - 200_000.0 * s
        let xR = widthEm - 400_000.0 * s
        guard let lc = makeCmds(data.paths[0], xShift: 0.0),
            let mc = makeCmds(data.paths[1], xShift: xM),
            let rc = makeCmds(data.paths[2], xShift: xR)
        else {
            // INTENTIONALLY UNCOVERED (defensive guard KEEP — see makeCmds).
            return nil
        }
        // KaTeX `stretchy.ts` + `katex.scss`: three stacked spans with overflow hidden —
        // `.brace-left` 25.1%, `.brace-center` 50% at left 25%, `.brace-right` 25.1% from the
        // right. Each child SVG is 400em wide with `preserveAspectRatio` slice so only the
        // correct horizontal band shows. Clipping all three to `[0, width]` exposes the
        // middle glyph’s full 400-unit shaft on the entire width → thick bar past the curls.
        let key = label.hasPrefix("\\") ? String(label.drop(while: { $0 == "\\" })) : label
        let w = widthEm
        let out: [PathCommand]
        if key == "overbrace" || key == "underbrace" {
            let leftMax = w * 0.251
            let centerMin = w * 0.25
            let centerMax = w * 0.75
            let rightMin = w * (1.0 - 0.251)
            var o = clipPathToRect(lc, xMin: 0.0, xMax: leftMax, yMin: yMin, yMax: yMax)
            o.append(
                contentsOf: clipPathToRect(
                    mc, xMin: centerMin, xMax: centerMax, yMin: yMin, yMax: yMax))
            o.append(
                contentsOf: clipPathToRect(rc, xMin: rightMin, xMax: w, yMin: yMin, yMax: yMax))
            out = o
        } else {
            // INTENTIONALLY UNCOVERED (defensive-fallback KEEP): overbrace
            // and underbrace are the only 3-path entries in
            // `katexImageData`, so this generic 3-piece branch has no
            // reachable label today. Kept as the correct KaTeX `stretchy.ts`
            // behavior should a new 3-path element ever be added.
            var o = clipPathToRect(lc, xMin: 0.0, xMax: w, yMin: yMin, yMax: yMax)
            o.append(contentsOf: clipPathToRect(mc, xMin: 0.0, xMax: w, yMin: yMin, yMax: yMax))
            o.append(contentsOf: clipPathToRect(rc, xMin: 0.0, xMax: w, yMin: yMin, yMax: yMax))
            out = o
        }
        return (out, heightEm)
    default:
        // INTENTIONALLY UNCOVERED (defensive-fallback KEEP): every
        // `katexImageData` entry has 1, 2, or 3 paths; a different count is
        // impossible with the current static table. Kept so a malformed
        // future entry fails soft (nil) rather than crashing.
        return nil
    }
}

func mapPathXYHorizontalToVerticalCd(
    _ cmds: [PathCommand], _ map: (Double, Double) -> (Double, Double)
) -> [PathCommand] {
    cmds.map { c in
        switch c {
        case .moveTo(let x, let y):
            let (nx, ny) = map(x, y)
            return .moveTo(x: nx, y: ny)
        case .lineTo(let x, let y):
            let (nx, ny) = map(x, y)
            return .lineTo(x: nx, y: ny)
        case .cubicTo(let x1, let y1, let x2, let y2, let x, let y):
            let (n1x, n1y) = map(x1, y1)
            let (n2x, n2y) = map(x2, y2)
            let (nx, ny) = map(x, y)
            return .cubicTo(x1: n1x, y1: n1y, x2: n2x, y2: n2y, x: nx, y: ny)
        case .quadTo(let x1, let y1, let x, let y):
            let (n1x, n1y) = map(x1, y1)
            let (nx, ny) = map(x, y)
            return .quadTo(x1: n1x, y1: n1y, x: nx, y: ny)
        case .close:
            return .close
        }
    }
}

/// Vertical `{CD}` ↑ / ↓: same filled KaTeX SVG as horizontal `\cdrightarrow`, rotated into the column.
///
/// Horizontal stretchy path uses x ∈ [0, `totalHeightEm`] (shaft length) and thin y-extent; we map
/// `(x,y) → (y_lateral + y, x - row_height)` (down) or mirrored for up so the arrowhead matches the
/// proven horizontal renderer in ``katexStretchyPath``.
func katexCdVertArrowFromRightarrow(
    down: Bool, totalHeightEm: Double, axisHeightEm: Double
) -> (commands: [PathCommand], lateralEm: Double)? {
    let rowDepth = max(totalHeightEm / 2.0 - axisHeightEm, 0.0)
    let rowHeight = totalHeightEm - rowDepth
    guard let (cmdsH, lateralEm) = katexStretchyPath("\\cdrightarrow", widthEm: totalHeightEm)
    else {
        // INTENTIONALLY UNCOVERED (defensive-fallback KEEP): the label is
        // the literal "\\cdrightarrow", which has a `katexImageData` entry
        // whose single path name resolves in `pathForName`, so the lookup
        // never fails. Kept so a table regression degrades to no-arrow
        // rather than crashing CD layout.
        return nil
    }
    let wLat = lateralEm
    let cmds =
        if down {
            mapPathXYHorizontalToVerticalCd(cmdsH) { xh, yh in (wLat / 2.0 + yh, xh - rowHeight) }
        } else {
            mapPathXYHorizontalToVerticalCd(cmdsH) { xh, yh in (wLat / 2.0 + yh, rowDepth - xh) }
        }
    return (cmds, lateralEm)
}
